version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: webdb
      # MYSQL_USER: party
      # MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
  web:
    build: .
    container_name: www
    depends_on:
      - db
    volumes:
      - ./htdocs/:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links: 
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234